# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '工数'), (1, '产值'), (2, '计划对应产值')])),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')])),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dept.Dept')),
            ],
        ),
        migrations.CreateModel(
            name='PlanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('saveTime', models.DateTimeField()),
                ('plname', models.CharField(max_length=100, unique=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')])),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')])),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plname', models.CharField(db_index=True, max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')])),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.IntegerField(choices=[(1, '男'), (0, '女')])),
                ('status', models.IntegerField(choices=[(1, '在职'), (0, '离职')])),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.Dept')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.SalesPlan'),
        ),
        migrations.AddField(
            model_name='price',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.Project'),
        ),
        migrations.AddField(
            model_name='actualresult',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.SalesPlan'),
        ),
        migrations.AddField(
            model_name='actualresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.Project'),
        ),
    ]
